' Needs rework
' Error found:
' Fail to get files to conduct operations

Private folderPath As String
Private yesterdaysWB As Workbook
Private todaysWB As Workbook
Private today As Date

Private yesterdaysWS As Worksheet
Private todaysWS As Worksheet

Public Sub Initialize(folderPath As String)

End Sub

Public Sub TransferNotes()

End Sub

Private Sub GetXLSXFiles()

End Sub

Private Sub GetXLSXFile(fileName As String) As Workbook

End Sub

Private Sub GetWorkSheets()

End Sub

Private Sub CloseWorkbooks()
    
End Sub
